GET http://localhost:3000/api/short-links

###
GET http://localhost:3000/api/short-links/123

###
GET http://localhost:3000/api/short-links/123?q=codeit123

###
POST http://localhost:3000/api/short-links/123
Content-Type: application/json

{"title": "codeit-shortit"}

###
PATCH http://localhost:3000/api/short-links/123
Content-Type: application/json

{"title": "codeit-shortit"}

###
GET http://localhost:3000/api/short-links/123
Cookie: session-id=codeit-1234

### QRCodes
###
GET http://localhost:3000/api/qrcodes

###
POST http://localhost:3000/api/qrcodes

###
PATCH http://localhost:3000/api/qrcodes

###
GET http://localhost:3000/api/qrcodes/abc

###
PATCH http://localhost:3000/api/qrcodes/abc
Content-Type: application/json

{
  "title": "위키피디아 Next.js",
  "url": "https://en.wikipedia.org/wiki/Next.js"
}

###
DELETE http://localhost:3000/api/qrcodes/abc

###
POST http://localhost:3000/api/qrcodes/abc